USE QuestionDB
CREATE TABLE Question(
	Q_ID INT NOT NULL IDENTITY(1,1),
	Q_QuestionText nVARCHAR(450) NOT NULL UNIQUE,
	Q_QA_ID INT NOT NULL,
	PRIMARY KEY(Q_ID),
	CONSTRAINT FK_QA_ID FOREIGN KEY (Q_QA_ID) REFERENCES QuestionAnswer(QA_ID)
);

CREATE TABLE Answer(
	A_ID INT NOT NULL IDENTITY (1,1),
	A_AnswerText nVARCHAR(450) NOT NULL UNIQUE,
	PRIMARY KEY(A_ID)
);

CREATE TABLE QuestionAnswer(
	QA_ID INT NOT NULL IDENTITY(1,1),
	QA_A_ID INT NOT NULL,
	QA_Q_ID INT NOT NULL,
	QA_IsCorrectAnswer BIT NOT NULL DEFAULT 0,
	PRIMARY KEY(QA_ID),
	CONSTRAINT FK_A_ID FOREIGN KEY (QA_A_ID) REFERENCES Answer(A_ID),
	CONSTRAINT FK_Q_ID FOREIGN KEY (QA_Q_ID) REFERENCES Question(Q_ID),
);

CREATE TABLE Player(
	P_ID INT NOT NULL,
	PRIMARY KEY(P_ID)
);

CREATE TABLE PlayerQuestionAnswer(
	PQA_ID INT NOT NULL IDENTITY(1,1),
	PQA_Q_ID INT NOT NULL,
	PQA_P_ID INT NOT NULL,
	PQA_IsAnswered BIT NOT NULL,
	PQA_IsCorrect BIT NOT NULL,
	PRIMARY KEY(PQA_ID),
	CONSTRAINT FK_PQA_Q_ID FOREIGN KEY (PQA_Q_ID) REFERENCES dbo.Question(Q_ID),
	CONSTRAINT FK_P_ID FOREIGN KEY (PQA_P_ID) REFERENCES dbo.Player(P_ID),
);